const getTitle = (path) => path.slice(1, path.lenght).split('/').join(' / ')
  .replace(/dashboard/g, 'Панель управления')
  .replace(/home/g, 'Главная')
  .replace(/profile/g, 'Профиль')
  .replace(/settings/g, 'Настройки')
  .replace(/security/g, 'Безопасность')
  .replace(/activities/g, 'Активность')
  .replace(/partner/g, 'Партнерская программа')
  .replace(/support/g, 'Поддержка')
  .replace(/tickets/g, 'Запросы в поддержку')
  .replace(/ticket/g, 'Запросы в поддержку')
  .replace(/new/g, 'Новый')
  .replace(/finance/g, 'Финансы')
  .replace(/faq/g, 'База знаний')
  .replace(/cryptowallets/g, 'Криптокошельки')
  .replace(/wallets/g, 'Кошельки')
  .replace(/qiwi/g, 'Qiwi')
  .replace(/shops/g, 'Магазины')
  .replace(/statistics/g, 'Статистика')
  .replace(/shipment/g, 'Продукция')
  .replace(/datas/g, 'Данные')
  .replace(/bots/g, 'Боты')
  .replace(/site/g, 'Сайт')
  .replace(/settings/g, 'Настройки')
  .replace(/feedback/g, 'Обратная связь');

export { getTitle };
